### ISSUE TITLE
Headers | link: rel=modulepreload support/capability

### ISSUE THREAD

**Issue by patriciatrauman** [Polymer/prpl-server#106]
So far, all link are set as `rel=preload`.
It could be useful to choose if we want `preload` or `modulepreload`.
So the browser wouldn't load twice a module file and avoid this kind of warning
![Screenshot 2021-06-18 at 15 47 59](https://user-images.githubusercontent.com/66091127/122571013-945ac280-d04c-11eb-9187-915c9673e6fd.png)

To do so, we could add an optional argument to push-manifest.json.
This could be implemented in https://github.com/Polymer/prpl-server/blob/master/src/push.ts 

Here is a possible implementation :
<img width="721" alt="Screenshot 2021-06-18 at 15 09 46" src="https://user-images.githubusercontent.com/66091127/122565880-3c6d8d00-d047-11eb-95b9-ef607e13491e.png">
<img width="398" alt="Screenshot 2021-06-18 at 15 10 03" src="https://user-images.githubusercontent.com/66091127/122565914-455e5e80-d047-11eb-9c63-acbf1d149ff3.png">
<img width="601" alt="Screenshot 2021-06-18 at 15 10 26" src="https://user-images.githubusercontent.com/66091127/122565964-527b4d80-d047-11eb-86d7-779b03651a1b.png">
<img width="572" alt="Screenshot 2021-06-18 at 15 13 28" src="https://user-images.githubusercontent.com/66091127/122566350-bf8ee300-d047-11eb-8d68-c36705221618.png">
<img width="499" alt="Screenshot 2021-06-18 at 15 10 43" src="https://user-images.githubusercontent.com/66091127/122566004-5c9d4c00-d047-11eb-80c9-6671159c13fc.png">

@aomarks
What do you think ? Does it make sense ?

**references :** 
https://developers.google.com/web/updates/2017/12/modulepreload
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/modulepreload

**Comment by aomarks** [comment]
Thank you for the feature request. Closing because we are no longer accepting new feature requests for prpl-server.

See https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives.
