### ISSUE TITLE
choose polyfill based on user agent

### ISSUE THREAD

**Issue by aomarks** [Polymer/prpl-server#35]
As suggested at https://github.com/WebComponents/webcomponentsjs#how-to-use, prpl-server could use its capability matrix to automatically chose the minimum required polyfill bundle based on the user agent.

One option is to dynamically rewrite the entry point HTML to include the detected polyfill bundle script tag.

Another idea is to use `webcomponents-loader.js` in the entrypoint, but *push* the bundle we *expect* the client will ultimately request. This way if we predict wrong, the browser can still request the correct polyfill.

**Comment by JosefJezek** [comment]
Please support for other polyfills, like as this project https://polyfill.io

**Comment by aomarks** [comment]
Closing because prpl-server is now in maintenance mode. See https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives.
