### ISSUE TITLE
Document support for, or how to deploy on, Google Cloud/Firebase Functions

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/prpl-server#63]

**Comment by anudeepsai** [comment]
Can we expect this in Polymer 3 ?

Thanks!

**Comment by jpeg729** [comment]
What would be really awesome would be to be able to upload the various static builds plus a few config files to firebase static hosting and have all of this work automatically via the Google CDN.

For example, I would add the following files

* builds.json config file for differential serving
* push-manifest.json for http/2 push
* cache-control.json containing caching rules for different assets

**Comment by Dabolus** [comment]
@keanulee and I are working on a small guide that explains how to deploy PWA Starter Kit with PRPL Server to Firebase Functions [here](https://github.com/Polymer/pwa-starter-kit/issues/135). I think that - once that the steps have been polished out - a more generalized guide can be written on top of that one and added in the docs here

**Comment by aomarks** [comment]
Closing because we are no longer accepting new feature requests for prpl-server. See https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives.
