### ISSUE TITLE
possible reverse proxy solution: nginx

### ISSUE THREAD

**Issue by nika-begiashvili** [Polymer/prpl-server#64]
recently nginx released new version, introducing link preload header upgrade

https://www.nginx.com/blog/nginx-1-13-9-http2-server-push/#automatic-push

maybe it's worth testing and putting into readme as alternative reverse proxy solution ?

**Comment by nika-begiashvili** [comment]
I've tested nginx and it works great! I think you should add that to your readme

**Comment by jkanche** [comment]
@nika-begiashvili I'm trying to do something similar where I would like to  setup the polymer app on `/app` and forward all these requests to `prpl-server`

Were you able to make it work with nginx ?

**Comment by nika-begiashvili** [comment]
Yes tha't basic nginx functionality, you should be able to do that

**Comment by jkanche** [comment]
I am running into the same issue as described in this post from a couple of years ago - https://stackoverflow.com/questions/48673689/serving-polymer-pwa-with-nginx-reverse-proxy
