### ISSUE TITLE
Entrypoint will not be served when serving from a non-root base path

### ISSUE THREAD

**Issue by sebaruth** [Polymer/prpl-server#78]
I am using this project to serve an polymer app from a non-root base path lets say "/examplePath/" with multiple builds for different browser capabilities. Everything works as expected meaning the entry point is served for every "non existing, non file" location, except when I try to browse directly to the specified non-root base path "/examplePath/". In this case I get an 404 error. 

I think the reason for that is that the "/examplePath/" is an actual folder on the server and thus the check if the file exists returns true, resulting in the server to try to serve this folder (see code snippet below from prpl.ts).   

```    
    // Serve the entrypoint for the root path, and for all other paths that
    // don't have a corresponding static resource on disk. As a special
    // case, paths with file extensions are always excluded because they are
    // likely to be not-found static resources rather than application
    // routes.
    const serveEntrypoint = urlPath === '/' ||
        (!hasFileExtension.test(urlPath) && !(await fileExists(absFilepath)));
```  
In my opinion this behavior should be changed, because browsing to the base path should reveal the entry point. 

My suggestion to fix this issue would be either to check for the non-root base path directly in the `serveEntrypoint` condition or to alter the `fileExists` method to only check for existing file and not for folders. 

One more note: when using a service worker this behavior occurs only on the first loading of the page. In order to reproduce this error u have to clear the browser cache.

King regards.

**Comment by aomarks** [comment]
Thank you for the report. Apologies for the very delayed response. As of today prpl-server is deprecated, so it will only be accepting critical bug and security fixes going forward. Please see https://github.com/Polymer/prpl-server#deprecation for details and recommended alternatives.
