### ISSUE TITLE
Allow configure Rendertron middleware when using CLI

### ISSUE THREAD

**Issue by mskasal** [Polymer/prpl-server#83]
I would like to configure Rendertron when I am using [CLI](https://github.com/Polymer/prpl-server/blob/1e66a56002b294a8121a6089735690b7c45580f4/src/cli.ts#L160) which using [Rendertron middleware](https://github.com/GoogleChrome/rendertron/tree/master/middleware#configuration).

I believe these options quite important.

For instance, I want to skip `image` renderings sake of performance. 
I am able to do that when I use middleware like this;

```javascript
app.use(rendertron.makeMiddleware({
    proxyUrl: args['bot-proxy'],
    injectShadyDom: true,
    excludeUrlPattern: new RegExp('png|jpeg', 'i') // --> I added this line in (https://github.com/Polymer/prpl-server/blob/1e66a56002b294a8121a6089735690b7c45580f4/src/cli.ts#L160)
}));
```

If I am missing something or there are a better options to achieve these please tell me.
Thanks.

**Comment by aomarks** [comment]
I believe you would want to use the rendertron middleware directly for this use case: https://github.com/GoogleChrome/rendertron/tree/main/middleware

Apologies for the extremely slow response :)

Also please note that prpl-server is now in maintenance mode. Please see https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives.
