### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by peterlauri** [Polymer/prpl-server#89]
Is it possible to enable logging for debug purposes?

**Comment by aomarks** [comment]
There is not currently any logging, but that's a reasonable feature request.

**Comment by aomarks** [comment]
Thank you for the feature request. Closing because we are no longer accepting new feature requests for prpl-server.

See https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives.
