### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by alexandru-tomescu** [Polymer/prpl-server#90]
Hi all ! How can i inject some variables when starting the server via command to be available via process.env[<env_variable>] ?

**Comment by keanulee** [comment]
`NODE_ENV=production prpl-server`

https://stackoverflow.com/questions/9198310/how-to-set-node-env-to-production-development-in-os-x

**Comment by alexandru-tomescu** [comment]
@keanulee My bad, I was doing something badly. Thank you for you response.
