### ISSUE TITLE
Custom response headers

### ISSUE THREAD

**Issue by lpellegr** [Polymer/prpl-server#93]
It looks like there is no mean to configure HTTP response headers with the CLI command. For instance, that's an issue since there is no mean to prevent _Clickjacking_: we cannot set an `X-Frame-Options` response header to content served by _prpl-server_.

**Comment by aomarks** [comment]
Thank you for the feature request. Closing because we are no longer accepting new feature requests for prpl-server.

See https://github.com/Polymer/prpl-server#prpl-server for our recently added maintenance mode notice, and recommendations for alternatives.

**Comment by laurentpellegrino** [comment]
@aomarks That's funny to read such an answer more than 2 years after the original issue was posted...

**Comment by aomarks** [comment]
> @aomarks That's funny to read such an answer more than 2 years after the original issue was posted...

Yes sorry about that :/
